### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by keefehuang**
Major update to clean up code.
- Added circuit_gate helper function to generate CircuitGate objects. 
```
    circuit_gate(target_wire::Int, g::AbstractGate, control_wires::Int...) 
```
- Removed CircuitGateChain object to remove one layer of abstraction. Now abstractions go AbstractGate -> CircuitGate -> Moments -> Circuit
- Added customized MeasurementOperator objects, these are now represented as sparse matrices to make more efficient
- Shifted number of wires out of parametrization, this prevents type stability
- Created custom _matrix function to create sparse matrices for ControlledGate objects more efficiently
- Updated apply() methods to be more type stable -> Needs future update to improve performance

### CODE REVIEW

**Comment by cmendl** [comment]
Can we let matrix(g) (with 'g' some gate) return a dense matrix, and rename matrix(cg::CircuitGate) to sparsematrix(cg::CircuitGate)? Why is there a separate  "_matrix" function for CircuitGate?

**Comment by cmendl** [comment]
The naming "size" in size(cg::CircuitGate) is a bit confusing; maybe rename to "required_wires" or similar?

**Comment by cmendl** [comment]
"get_data" at the end of gates.jl presumably no longer required...

**Comment by cmendl** [comment]
The naming "compile.jl" is somewhat confusing, rename to "unitary2circuit.jl" or similar?

**Comment by cmendl** [comment]
circuitgate.jl, line 77: Int[i for i in cg.iwire] can be replaced by collect(cg.iwire). (There might be other occurrences as well.)

**Comment by cmendl** [comment]
One level of indentation missing at cricuit.jl, line 164

**Comment by keefehuang** [comment]
- updated sparse_matrix and related functions
- updated size to num_wires -> Also used for gates and returns Int with number of wires/qubits required
- get_data is a helper function that doesn't error when querying gates for info -> hard to differentiate between gates with no variable data etc. 
- updated compile.j names
- updated collect instead of list compre. 
-

**Comment by cmendl** [comment]
> "get_data" at the end of gates.jl presumably no longer required...

can we remove get_data?

**Pull request merged**
